[project]
name = "lazy-ansible"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "ansible>=11.7.0",
    "argcomplete>=3.6.2",
]
